package com.xianxia.sect.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate

/**
 * KSP 处理器：扫描 @ExposeDelegates 注解，为 @Embedded 字段生成委托扩展属性。
 *
 * 采用标准的 KSP 多轮处理模式：首轮编译注解类，次轮找到注解并生成代码。
 */
class DelegateFieldProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val symbols = resolver.getSymbolsWithAnnotation(
            "com.xianxia.sect.core.state.ExposeDelegates"
        ).toList()

        // 多轮处理：过滤掉尚未 validate 的符号，延迟到下一轮
        val validSymbols = symbols.filter { it.validate() }
        val deferred = symbols.filter { !it.validate() }

        if (validSymbols.isEmpty()) return deferred

        val annotatedFields = validSymbols.filterIsInstance<KSPropertyDeclaration>()

        val grouped = annotatedFields.groupBy { it.parentDeclaration }
        if (grouped.isEmpty()) return deferred

        val generatedCode = buildString {
            appendLine("// Auto-generated by DelegateFieldProcessor — DO NOT EDIT")
            appendLine("package com.xianxia.sect.core.model")
            appendLine()

            for ((parentClass, fields) in grouped) {
                val className = parentClass?.simpleName?.asString() ?: continue
                appendLine("/**")
                appendLine(" * @ExposeDelegates 生成的委托扩展属性 — [$className]")
                appendLine(" */")

                for (field in fields) {
                    val fieldName = field.simpleName.asString()
                    val annotation = field.annotations.firstOrNull {
                        it.shortName.asString() == "ExposeDelegates"
                    } ?: continue
                    val propertiesArg = annotation.arguments.firstOrNull { it.name?.asString() == "properties" }
                        ?: continue
                    val propertyNames = (propertiesArg.value as? List<*>)?.mapNotNull { it as? String }
                        ?: continue

                    val fieldType = field.type.resolve()
                    val fieldTypeDecl = fieldType.declaration as? KSClassDeclaration ?: continue

                    for (propName in propertyNames) {
                        val sourceProp = fieldTypeDecl.getAllProperties()
                            .find { it.simpleName.asString() == propName }
                        if (sourceProp == null) {
                            logger.warn("Property '$propName' not found in ${fieldTypeDecl.simpleName.asString()}")
                            continue
                        }
                        val propType = sourceProp.type.resolve()
                        val typeName = propType.declaration.qualifiedName?.asString()
                            ?: propType.declaration.simpleName.asString()

                        appendLine()
                        appendLine("/** @deprecated 请改用 [$fieldName.$propName] */")
                        appendLine("var $className.$propName: $typeName")
                        appendLine("    get() = $fieldName.$propName")
                        appendLine("    set(value) { $fieldName.$propName = value }")
                    }
                }
            }
        }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(false),
            packageName = "com.xianxia.sect.core.model",
            fileName = "ExposedDelegatesGenerated"
        )
        file.writer().use { it.write(generatedCode) }

        generated = true
        return deferred
    }
}

class DelegateFieldProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return DelegateFieldProcessor(environment.codeGenerator, environment.logger)
    }
}
