package com.xianxia.sect.ksp

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate

/**
 * KSP 处理器：扫描 @DelegateField 注解，生成委托属性代码。
 *
 * 输入：
 * ```kotlin
 * @DelegateField(source = "combat", property = "baseHp")
 * var baseHp: Int
 * ```
 *
 * 输出（DelegateFieldGenerated.kt）：
 * ```kotlin
 * var Disciple.baseHp: Int
 *     get() = combat.baseHp
 *     set(value) { combat.baseHp = value }
 * ```
 */
class DelegateFieldProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val annotatedDeclarations = resolver.getSymbolsWithAnnotation(
            "com.xianxia.sect.core.state.DelegateField"
        ).filterIsInstance<KSPropertyDeclaration>().toList()

        if (annotatedDeclarations.isEmpty()) return emptyList()

        val generatedCode = buildString {
            appendLine("// Auto-generated by DelegateFieldProcessor — DO NOT EDIT")
            appendLine("package com.xianxia.sect.core.model")
            appendLine()

            // Group by parent class
            val grouped = annotatedDeclarations.groupBy { it.parentDeclaration }
            for ((parentClass, properties) in grouped) {
                val className = parentClass?.simpleName?.asString() ?: continue
                appendLine("/**")
                appendLine(" * @DelegateField 生成的委托属性 — [$className]")
                appendLine(" */")

                for (prop in properties) {
                    val annotation = prop.annotations.first {
                        it.shortName.asString() == "DelegateField"
                    }
                    val source = annotation.arguments.find { it.name?.asString() == "source" }?.value as? String ?: continue
                    val property = (annotation.arguments.find { it.name?.asString() == "property" }?.value as? String)
                        ?.ifEmpty { prop.simpleName.asString() }
                        ?: prop.simpleName.asString()
                    val propName = prop.simpleName.asString()
                    val propType = prop.type.resolve().declaration.simpleName.asString()

                    // Skip if the property already has a getter/setter body (not a delegate)
                    val hasGetter = prop.getter != null
                    val hasSetter = prop.setter != null
                    if (hasGetter || hasSetter) {
                        logger.info("Skipping $propName — already has getter/setter")
                        continue
                    }

                    appendLine("var $className.$propName: $propType")
                    appendLine("    get() = $source.$property")
                    appendLine("    set(value) { $source.$property = value }")
                }
            }
        }

        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(false),
            packageName = "com.xianxia.sect.core.model",
            fileName = "DelegateFieldGenerated"
        )
        file.writer().use { it.write(generatedCode) }

        return emptyList()
    }
}

class DelegateFieldProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return DelegateFieldProcessor(environment.codeGenerator, environment.logger)
    }
}
