package com.xianxia.sect.ui.components

/**
 * 精灵图分类 — 决定预加载优先级。
 * priority: 0 = L0（首屏必须），1 = L1（重要界面），2 = L2（后台加载）
 */
enum class SpriteCategory(val priority: Int) {
    UI(0),
    PORTRAIT(0),
    ITEM(1),
    BUILDING(1),
    EQUIPMENT(1),
    MANUAL(1),
    PILL(1),
    BEAST(2),
    CAVE(2),
    HEAVENLY_TRIAL(2),
    BACKGROUND(1),
    MAP(1),
    MATERIAL(2),
    STORAGE_BAG(2),
    SPIRIT_STONE(2),
    SECT_ICON(2)
}

/**
 * Registry for sprite drawable resource IDs.
 * The app module must register sprites at startup via [register]
 * (generated by scripts/build-atlas.mjs --codegen → SpriteRegistryData.registerAllSprites),
 * since library modules cannot reference the app module's R class.
 *
 * 精灵图分类统一通过 [register] 注册，通过 [resolve] 按名称查找，
 * 通过 [categoryResIds] 供 ResourcePreloader 自动发现。
 */
object SpriteResRegistry {

    /** 按分类存储 name→resId 映射（统一注册入口） */
    private val categoryMaps = mutableMapOf<SpriteCategory, Map<String, Int>>()

    /**
     * 注册一个精灵图分类下的所有资源映射。
     * 应在 [com.xianxia.sect.XianxiaApplication.onCreate] 中调用。
     */
    fun register(category: SpriteCategory, sprites: Map<String, Int>) {
        categoryMaps[category] = sprites
    }

    /**
     * 遍历所有已注册分类，按名称查找精灵图资源 ID。
     * @return 找到的第一个匹配 resId，未找到返回 null
     */
    fun resolve(name: String): Int? {
        for ((_, sprites) in categoryMaps) {
            sprites[name]?.let { return it }
        }
        return null
    }

    /**
     * 在指定分类下按名称查找精灵图资源 ID。
     * 优先用于存在跨分类重名时（如 spirit_stone_* 在 SPIRIT_STONE 与 UI 双注册）。
     * @return 匹配 resId，未找到返回 null
     */
    fun categoryResId(category: SpriteCategory, name: String): Int? =
        categoryMaps[category]?.get(name)

    /**
     * 获取指定分类下的所有资源 ID。
     * 供 ResourcePreloader 按分类预加载。
     */
    fun categoryResIds(category: SpriteCategory): List<Int> =
        categoryMaps[category]?.values?.toList() ?: emptyList()

    /**
     * 获取所有已注册分类的精灵图资源 ID（去重）。
     */
    fun allResIds(): List<Int> =
        categoryMaps.values.flatMap { it.values }.distinct()
}

// ── 预加载聚合器（ResourcePreloader 发现域） ──

fun allPillSpriteResIds(): List<Int> = (1..6).mapNotNull { pillSpriteRes(it) }

fun allManualSpriteResIds(): List<Int> = (1..6).mapNotNull { manualSpriteRes(it) }

fun allEquipmentSpriteResIds(): List<Int> =
    SpriteResRegistry.categoryResIds(SpriteCategory.EQUIPMENT)
