package com.xianxia.sect.core.state

@Suppress("LongMethod")
internal fun DiscipleTables.buildCopyableRefs(): List<CopyableTableRef> = listOf(
    // ── Int 表（值拷贝） ──
    IntTableRef(slotIds, DiscipleTables::slotIds, "slotIds"),
    IntTableRef(realms, DiscipleTables::realms, "realms"),
    IntTableRef(realmLayers, DiscipleTables::realmLayers, "realmLayers"),
    IntTableRef(isAlive, DiscipleTables::isAlive, "isAlive"),
    IntTableRef(deathYears, DiscipleTables::deathYears, "deathYears"),
    IntTableRef(cultivationSpeedDurations, DiscipleTables::cultivationSpeedDurations, "cultivationSpeedDurations"),
    IntTableRef(baseHps, DiscipleTables::baseHps, "baseHps"),
    IntTableRef(baseMps, DiscipleTables::baseMps, "baseMps"),
    IntTableRef(baseAttacks, DiscipleTables::baseAttacks, "baseAttacks"),
    IntTableRef(baseDefenses, DiscipleTables::baseDefenses, "baseDefenses"),
    IntTableRef(baseSpeeds, DiscipleTables::baseSpeeds, "baseSpeeds"),
    IntTableRef(hpVariances, DiscipleTables::hpVariances, "hpVariances"),
    IntTableRef(mpVariances, DiscipleTables::mpVariances, "mpVariances"),
    IntTableRef(attackVariances, DiscipleTables::attackVariances, "attackVariances"),
    IntTableRef(defenseVariances, DiscipleTables::defenseVariances, "defenseVariances"),
    IntTableRef(speedVariances, DiscipleTables::speedVariances, "speedVariances"),
    IntTableRef(breakthroughCounts, DiscipleTables::breakthroughCounts, "breakthroughCounts"),
    IntTableRef(breakthroughFailCounts, DiscipleTables::breakthroughFailCounts, "breakthroughFailCounts"),
    IntTableRef(currentHps, DiscipleTables::currentHps, "currentHps"),
    IntTableRef(currentMps, DiscipleTables::currentMps, "currentMps"),
    IntTableRef(pillAttackBonuses, DiscipleTables::pillAttackBonuses, "pillAttackBonuses"),
    IntTableRef(pillHpBonuses, DiscipleTables::pillHpBonuses, "pillHpBonuses"),
    IntTableRef(pillMpBonuses, DiscipleTables::pillMpBonuses, "pillMpBonuses"),
    IntTableRef(pillSpeedBonuses, DiscipleTables::pillSpeedBonuses, "pillSpeedBonuses"),
    IntTableRef(pillEffectDurations, DiscipleTables::pillEffectDurations, "pillEffectDurations"),
    IntTableRef(discipleSpiritStones, DiscipleTables::discipleSpiritStones, "discipleSpiritStones"),
    IntTableRef(cultivationCompletionMonths, DiscipleTables::cultivationCompletionMonths,
        "cultivationCompletionMonths"),
    IntTableRef(manualCompletionMonths, DiscipleTables::manualCompletionMonths, "manualCompletionMonths"),
    IntTableRef(manualCompletionPhases, DiscipleTables::manualCompletionPhases, "manualCompletionPhases"),
    IntTableRef(intelligences, DiscipleTables::intelligences, "intelligences"),
    IntTableRef(charms, DiscipleTables::charms, "charms"),
    IntTableRef(comprehensions, DiscipleTables::comprehensions, "comprehensions"),
    IntTableRef(artifactRefinings, DiscipleTables::artifactRefinings, "artifactRefinings"),
    IntTableRef(pillRefinings, DiscipleTables::pillRefinings, "pillRefinings"),
    IntTableRef(spiritPlantings, DiscipleTables::spiritPlantings, "spiritPlantings"),
    IntTableRef(minings, DiscipleTables::minings, "minings"),
    IntTableRef(teachings, DiscipleTables::teachings, "teachings"),
    IntTableRef(moralities, DiscipleTables::moralities, "moralities"),
    IntTableRef(salaryPaidCounts, DiscipleTables::salaryPaidCounts, "salaryPaidCounts"),
    IntTableRef(salaryMissedCounts, DiscipleTables::salaryMissedCounts, "salaryMissedCounts"),
    IntTableRef(alchemyLevels, DiscipleTables::alchemyLevels, "alchemyLevels"),
    IntTableRef(alchemyPromotionCounts, DiscipleTables::alchemyPromotionCounts, "alchemyPromotionCounts"),
    IntTableRef(forgeLevels, DiscipleTables::forgeLevels, "forgeLevels"),
    IntTableRef(forgePromotionCounts, DiscipleTables::forgePromotionCounts, "forgePromotionCounts"),
    IntTableRef(recruitedMonths, DiscipleTables::recruitedMonths, "recruitedMonths"),
    IntTableRef(hasReviveEffects, DiscipleTables::hasReviveEffects, "hasReviveEffects"),
    IntTableRef(hasClearAllEffects, DiscipleTables::hasClearAllEffects, "hasClearAllEffects"),

    // ── Double 表（值拷贝） ──
    DoubleTableRef(cultivations, DiscipleTables::cultivations, "cultivations"),
    DoubleTableRef(cultivationCheckpoints, DiscipleTables::cultivationCheckpoints, "cultivationCheckpoints"),
    IntTableRef(cultivationCheckpointGameMonths, DiscipleTables::cultivationCheckpointGameMonths,
        "cultivationCheckpointGameMonths"),
    DoubleTableRef(cultivationSpeedBonuses, DiscipleTables::cultivationSpeedBonuses, "cultivationSpeedBonuses"),
    DoubleTableRef(pillCritRateBonuses, DiscipleTables::pillCritRateBonuses, "pillCritRateBonuses"),
    DoubleTableRef(pillCritEffectBonuses, DiscipleTables::pillCritEffectBonuses, "pillCritEffectBonuses"),
    DoubleTableRef(pillCultivationSpeedBonuses, DiscipleTables::pillCultivationSpeedBonuses,
        "pillCultivationSpeedBonuses"),
    DoubleTableRef(pillSkillExpSpeedBonuses, DiscipleTables::pillSkillExpSpeedBonuses, "pillSkillExpSpeedBonuses"),

    // ── Long 表（值不可变，浅拷贝安全） ──
    RefTableRef(totalCultivations, DiscipleTables::totalCultivations, "totalCultivations"),
    RefTableRef(storageBagSpiritStones, DiscipleTables::storageBagSpiritStones, "storageBagSpiritStones"),

    // ── String 表（引用不可变，浅拷贝安全） ──
    RefTableRef(names, DiscipleTables::names, "names"),
    RefTableRef(surnames, DiscipleTables::surnames, "surnames"),
    RefTableRef(genders, DiscipleTables::genders, "genders"),
    RefTableRef(portraitRes, DiscipleTables::portraitRes, "portraitRes"),
    RefTableRef(templateIds, DiscipleTables::templateIds, "templateIds"),
    RefTableRef(discipleTypes, DiscipleTables::discipleTypes, "discipleTypes"),
    RefTableRef(spiritRootTypes, DiscipleTables::spiritRootTypes, "spiritRootTypes"),
    RefTableRef(innateDamageTypes, DiscipleTables::innateDamageTypes, "innateDamageTypes"),
    RefTableRef(activePillCategories, DiscipleTables::activePillCategories, "activePillCategories"),
    RefTableRef(headIds, DiscipleTables::headIds, "headIds"),
    RefTableRef(bodyIds, DiscipleTables::bodyIds, "bodyIds"),
    RefTableRef(handsIds, DiscipleTables::handsIds, "handsIds"),
    RefTableRef(feetIds, DiscipleTables::feetIds, "feetIds"),
    RefTableRef(weaponIds, DiscipleTables::weaponIds, "weaponIds"),
    RefTableRef(legsIds, DiscipleTables::legsIds, "legsIds"),

    // ── Set 表（需深拷贝 toSet） ──
    MutableTableRef(activePillTypes, DiscipleTables::activePillTypes, "activePillTypes") { it.toSet() },
    MutableTableRef(usedPermanentPillKeys, DiscipleTables::usedPermanentPillKeys,
        "usedPermanentPillKeys") { it.toSet() },

    // ── List 表（需深拷贝 toList） ──
    MutableTableRef(manualIds, DiscipleTables::manualIds, "manualIds") { it.toList() },
    MutableTableRef(lifeEvents, DiscipleTables::lifeEvents, "lifeEvents") { it.toList() },
    MutableTableRef(storageBagItems, DiscipleTables::storageBagItems, "storageBagItems") { it.toList() },
    MutableTableRef(usedFunctionalPillTypes, DiscipleTables::usedFunctionalPillTypes,
        "usedFunctionalPillTypes") { it.toList() },

    // ── Map 表（需深拷贝 toMap） ──
    MutableTableRef(manualMasteries, DiscipleTables::manualMasteries, "manualMasteries") { it.toMap() },
    MutableTableRef(statusData, DiscipleTables::statusData, "statusData") { it.toMap() },

    // ── 枚举/数据类单值表（值不可变，浅拷贝安全） ──
    RefTableRef(statuses, DiscipleTables::statuses, "statuses"),
)
