package com.xianxia.sect.core.state

@Suppress("LongMethod")
internal fun DiscipleTables.buildCopyableRefs(): List<CopyableTableRef> = listOf(
    // ── Int 表（值拷贝） ──
    IntTableRef(slotIds, DiscipleTables::slotIds, "slotIds"),
    IntTableRef(realms, DiscipleTables::realms, "realms"),
    IntTableRef(realmLayers, DiscipleTables::realmLayers, "realmLayers"),
    IntTableRef(ages, DiscipleTables::ages, "ages"),
    IntTableRef(lifespans, DiscipleTables::lifespans, "lifespans"),
    IntTableRef(isAlive, DiscipleTables::isAlive, "isAlive"),
    IntTableRef(deathYears, DiscipleTables::deathYears, "deathYears"),
    IntTableRef(soulPowers, DiscipleTables::soulPowers, "soulPowers"),
    IntTableRef(cultivationSpeedDurations, DiscipleTables::cultivationSpeedDurations, "cultivationSpeedDurations"),
    IntTableRef(baseHps, DiscipleTables::baseHps, "baseHps"),
    IntTableRef(baseMps, DiscipleTables::baseMps, "baseMps"),
    IntTableRef(basePhysicalAttacks, DiscipleTables::basePhysicalAttacks, "basePhysicalAttacks"),
    IntTableRef(baseMagicAttacks, DiscipleTables::baseMagicAttacks, "baseMagicAttacks"),
    IntTableRef(basePhysicalDefenses, DiscipleTables::basePhysicalDefenses, "basePhysicalDefenses"),
    IntTableRef(baseMagicDefenses, DiscipleTables::baseMagicDefenses, "baseMagicDefenses"),
    IntTableRef(baseSpeeds, DiscipleTables::baseSpeeds, "baseSpeeds"),
    IntTableRef(hpVariances, DiscipleTables::hpVariances, "hpVariances"),
    IntTableRef(mpVariances, DiscipleTables::mpVariances, "mpVariances"),
    IntTableRef(physicalAttackVariances, DiscipleTables::physicalAttackVariances, "physicalAttackVariances"),
    IntTableRef(magicAttackVariances, DiscipleTables::magicAttackVariances, "magicAttackVariances"),
    IntTableRef(physicalDefenseVariances, DiscipleTables::physicalDefenseVariances, "physicalDefenseVariances"),
    IntTableRef(magicDefenseVariances, DiscipleTables::magicDefenseVariances, "magicDefenseVariances"),
    IntTableRef(speedVariances, DiscipleTables::speedVariances, "speedVariances"),
    IntTableRef(breakthroughCounts, DiscipleTables::breakthroughCounts, "breakthroughCounts"),
    IntTableRef(breakthroughFailCounts, DiscipleTables::breakthroughFailCounts, "breakthroughFailCounts"),
    IntTableRef(currentHps, DiscipleTables::currentHps, "currentHps"),
    IntTableRef(currentMps, DiscipleTables::currentMps, "currentMps"),
    IntTableRef(pillPhysicalAttackBonuses, DiscipleTables::pillPhysicalAttackBonuses, "pillPhysicalAttackBonuses"),
    IntTableRef(pillMagicAttackBonuses, DiscipleTables::pillMagicAttackBonuses, "pillMagicAttackBonuses"),
    IntTableRef(pillPhysicalDefenseBonuses, DiscipleTables::pillPhysicalDefenseBonuses,
        "pillPhysicalDefenseBonuses"),
    IntTableRef(pillMagicDefenseBonuses, DiscipleTables::pillMagicDefenseBonuses, "pillMagicDefenseBonuses"),
    IntTableRef(pillHpBonuses, DiscipleTables::pillHpBonuses, "pillHpBonuses"),
    IntTableRef(pillMpBonuses, DiscipleTables::pillMpBonuses, "pillMpBonuses"),
    IntTableRef(pillSpeedBonuses, DiscipleTables::pillSpeedBonuses, "pillSpeedBonuses"),
    IntTableRef(pillEffectDurations, DiscipleTables::pillEffectDurations, "pillEffectDurations"),
    IntTableRef(discipleSpiritStones, DiscipleTables::discipleSpiritStones, "discipleSpiritStones"),
    IntTableRef(cultivationCompletionMonths, DiscipleTables::cultivationCompletionMonths,
        "cultivationCompletionMonths"),
    IntTableRef(cultivationCompletionPhases, DiscipleTables::cultivationCompletionPhases,
        "cultivationCompletionPhases"),
    IntTableRef(manualCompletionMonths, DiscipleTables::manualCompletionMonths, "manualCompletionMonths"),
    IntTableRef(manualCompletionPhases, DiscipleTables::manualCompletionPhases, "manualCompletionPhases"),
    IntTableRef(equipmentNurturingCompletionMonths, DiscipleTables::equipmentNurturingCompletionMonths,
        "equipmentNurturingCompletionMonths"),
    IntTableRef(equipmentNurturingCompletionPhases, DiscipleTables::equipmentNurturingCompletionPhases,
        "equipmentNurturingCompletionPhases"),
    IntTableRef(lastChildYears, DiscipleTables::lastChildYears, "lastChildYears"),
    IntTableRef(intelligences, DiscipleTables::intelligences, "intelligences"),
    IntTableRef(charms, DiscipleTables::charms, "charms"),
    IntTableRef(loyalties, DiscipleTables::loyalties, "loyalties"),
    IntTableRef(comprehensions, DiscipleTables::comprehensions, "comprehensions"),
    IntTableRef(artifactRefinings, DiscipleTables::artifactRefinings, "artifactRefinings"),
    IntTableRef(pillRefinings, DiscipleTables::pillRefinings, "pillRefinings"),
    IntTableRef(spiritPlantings, DiscipleTables::spiritPlantings, "spiritPlantings"),
    IntTableRef(minings, DiscipleTables::minings, "minings"),
    IntTableRef(teachings, DiscipleTables::teachings, "teachings"),
    IntTableRef(moralities, DiscipleTables::moralities, "moralities"),
    IntTableRef(aptitudes, DiscipleTables::aptitudes, "aptitudes"),
    IntTableRef(salaryPaidCounts, DiscipleTables::salaryPaidCounts, "salaryPaidCounts"),
    IntTableRef(salaryMissedCounts, DiscipleTables::salaryMissedCounts, "salaryMissedCounts"),
    IntTableRef(alchemyLevels, DiscipleTables::alchemyLevels, "alchemyLevels"),
    IntTableRef(alchemyPromotionCounts, DiscipleTables::alchemyPromotionCounts, "alchemyPromotionCounts"),
    IntTableRef(forgeLevels, DiscipleTables::forgeLevels, "forgeLevels"),
    IntTableRef(forgePromotionCounts, DiscipleTables::forgePromotionCounts, "forgePromotionCounts"),
    IntTableRef(recruitedMonths, DiscipleTables::recruitedMonths, "recruitedMonths"),
    IntTableRef(lastTheftJudgementYears, DiscipleTables::lastTheftJudgementYears, "lastTheftJudgementYears"),
    IntTableRef(hasReviveEffects, DiscipleTables::hasReviveEffects, "hasReviveEffects"),
    IntTableRef(hasClearAllEffects, DiscipleTables::hasClearAllEffects, "hasClearAllEffects"),

    // ── Double 表（值拷贝） ──
    DoubleTableRef(cultivations, DiscipleTables::cultivations, "cultivations"),
    DoubleTableRef(cultivationCheckpoints, DiscipleTables::cultivationCheckpoints, "cultivationCheckpoints"),
    IntTableRef(cultivationCheckpointGameMonths, DiscipleTables::cultivationCheckpointGameMonths,
        "cultivationCheckpointGameMonths"),
    DoubleTableRef(cultivationSpeedBonuses, DiscipleTables::cultivationSpeedBonuses, "cultivationSpeedBonuses"),
    DoubleTableRef(pillCritRateBonuses, DiscipleTables::pillCritRateBonuses, "pillCritRateBonuses"),
    DoubleTableRef(pillCritEffectBonuses, DiscipleTables::pillCritEffectBonuses, "pillCritEffectBonuses"),
    DoubleTableRef(pillCultivationSpeedBonuses, DiscipleTables::pillCultivationSpeedBonuses,
        "pillCultivationSpeedBonuses"),
    DoubleTableRef(pillSkillExpSpeedBonuses, DiscipleTables::pillSkillExpSpeedBonuses, "pillSkillExpSpeedBonuses"),
    DoubleTableRef(pillNurtureSpeedBonuses, DiscipleTables::pillNurtureSpeedBonuses, "pillNurtureSpeedBonuses"),

    // ── Long 表（值不可变，浅拷贝安全） ──
    RefTableRef(totalCultivations, DiscipleTables::totalCultivations, "totalCultivations"),
    RefTableRef(storageBagSpiritStones, DiscipleTables::storageBagSpiritStones, "storageBagSpiritStones"),

    // ── String 表（引用不可变，浅拷贝安全） ──
    RefTableRef(names, DiscipleTables::names, "names"),
    RefTableRef(surnames, DiscipleTables::surnames, "surnames"),
    RefTableRef(genders, DiscipleTables::genders, "genders"),
    RefTableRef(portraitRes, DiscipleTables::portraitRes, "portraitRes"),
    RefTableRef(discipleTypes, DiscipleTables::discipleTypes, "discipleTypes"),
    RefTableRef(spiritRootTypes, DiscipleTables::spiritRootTypes, "spiritRootTypes"),
    RefTableRef(activePillCategories, DiscipleTables::activePillCategories, "activePillCategories"),
    RefTableRef(weaponIds, DiscipleTables::weaponIds, "weaponIds"),
    RefTableRef(armorIds, DiscipleTables::armorIds, "armorIds"),
    RefTableRef(bootsIds, DiscipleTables::bootsIds, "bootsIds"),
    RefTableRef(accessoryIds, DiscipleTables::accessoryIds, "accessoryIds"),

    // ── Set 表（需深拷贝 toSet） ──
    MutableTableRef(activePillTypes, DiscipleTables::activePillTypes, "activePillTypes") { it.toSet() },
    MutableTableRef(usedPermanentPillKeys, DiscipleTables::usedPermanentPillKeys,
        "usedPermanentPillKeys") { it.toSet() },
    MutableTableRef(usedExtendLifePillTypes, DiscipleTables::usedExtendLifePillTypes,
        "usedExtendLifePillTypes") { it.toSet() },

    // ── List 表（需深拷贝 toList） ──
    MutableTableRef(manualIds, DiscipleTables::manualIds, "manualIds") { it.toList() },
    MutableTableRef(talentIds, DiscipleTables::talentIds, "talentIds") { it.toList() },
    MutableTableRef(physiqueIds, DiscipleTables::physiqueIds, "physiqueIds") { it.toList() },
    MutableTableRef(affixIds, DiscipleTables::affixIds, "affixIds") { it.toList() },
    MutableTableRef(lifeEvents, DiscipleTables::lifeEvents, "lifeEvents") { it.toList() },
    MutableTableRef(storageBagItems, DiscipleTables::storageBagItems, "storageBagItems") { it.toList() },
    MutableTableRef(usedFunctionalPillTypes, DiscipleTables::usedFunctionalPillTypes,
        "usedFunctionalPillTypes") { it.toList() },
    MutableTableRef(usedExtendLifePillIds, DiscipleTables::usedExtendLifePillIds,
        "usedExtendLifePillIds") { it.toList() },

    // ── Map 表（需深拷贝 toMap） ──
    MutableTableRef(manualMasteries, DiscipleTables::manualMasteries, "manualMasteries") { it.toMap() },
    MutableTableRef(statusData, DiscipleTables::statusData, "statusData") { it.toMap() },

    // ── 枚举/数据类单值表（值不可变，浅拷贝安全） ──
    RefTableRef(statuses, DiscipleTables::statuses, "statuses"),
    RefTableRef(weaponNurtures, DiscipleTables::weaponNurtures, "weaponNurtures"),
    RefTableRef(armorNurtures, DiscipleTables::armorNurtures, "armorNurtures"),
    RefTableRef(bootsNurtures, DiscipleTables::bootsNurtures, "bootsNurtures"),
    RefTableRef(accessoryNurtures, DiscipleTables::accessoryNurtures, "accessoryNurtures"),

    // ── Nullable 值表（值不可变，浅拷贝安全） ──
    RefTableRef(partnerIds, DiscipleTables::partnerIds, "partnerIds"),
    RefTableRef(partnerSectIds, DiscipleTables::partnerSectIds, "partnerSectIds"),
    RefTableRef(parentId1s, DiscipleTables::parentId1s, "parentId1s"),
    RefTableRef(parentId2s, DiscipleTables::parentId2s, "parentId2s"),
    IntTableRef(griefEndYears, DiscipleTables::griefEndYears, "griefEndYears"),
    RefTableRef(childBirthMonths, DiscipleTables::childBirthMonths, "childBirthMonths"),
    RefTableRef(masterIds, DiscipleTables::masterIds, "masterIds")
)
