package com.xianxia.sect.core.engine

import com.xianxia.sect.core.model.*
import com.xianxia.sect.core.util.DomainResult

fun GameEngine.addDisciple(disciple: Disciple) = discipleFacade.addDisciple(disciple)
fun GameEngine.removeDisciple(discipleId: String): DomainResult<Unit> = discipleFacade.removeDisciple(discipleId)
fun GameEngine.getDiscipleById(discipleId: String): Disciple? = discipleFacade.getDiscipleById(discipleId)
fun GameEngine.updateDisciple(disciple: Disciple) = discipleFacade.updateDisciple(disciple)
fun GameEngine.getDiscipleStatus(discipleId: String): DiscipleStatus = discipleFacade.getDiscipleStatus(discipleId)
fun GameEngine.syncAllDiscipleStatuses() = discipleFacade.syncAllDiscipleStatuses()
suspend fun GameEngine.resetAllDisciplesStatus() = discipleFacade.resetAllDisciplesStatus()
fun GameEngine.recruitDisciple(): Disciple = discipleFacade.recruitDisciple()
suspend fun GameEngine.expelDisciple(discipleId: String): DomainResult<Unit> = discipleFacade.expelDisciple(discipleId)
suspend fun GameEngine.expelTheftDisciple(discipleId: String): DomainResult<Unit> = discipleFacade.expelTheftDisciple(discipleId)
suspend fun GameEngine.imprisonTheftDisciple(discipleId: String, currentYear: Int) = discipleFacade.imprisonTheftDisciple(discipleId, currentYear)
suspend fun GameEngine.releaseTheftDisciple(discipleId: String): Int = discipleFacade.releaseTheftDisciple(discipleId)
fun GameEngine.clearPendingNotification() = discipleFacade.clearPendingNotification()
suspend fun GameEngine.approveMarriage(maleId: String, femaleId: String) = discipleFacade.approveMarriage(maleId, femaleId)
suspend fun GameEngine.equipEquipment(discipleId: String, equipmentId: String): DomainResult<Unit> = discipleFacade.equipEquipment(discipleId, equipmentId)
suspend fun GameEngine.unequipEquipment(discipleId: String, equipmentId: String): DomainResult<Unit> = discipleFacade.unequipEquipment(discipleId, equipmentId)
fun GameEngine.isDiscipleAssignedToSpiritMine(discipleId: String): Boolean = discipleFacade.isDiscipleAssignedToSpiritMine(discipleId)
fun GameEngine.updateYearlySalaryEnabled(realm: Int, enabled: Boolean) = discipleFacade.updateYearlySalaryEnabled(realm, enabled)
fun GameEngine.getAliveDisciplesCount(): Int = discipleFacade.getAliveDisciplesCount()
fun GameEngine.getIdleDisciples(): List<Disciple> = discipleFacade.getIdleDisciples()
suspend fun GameEngine.autoFillLawEnforcementSlots(): Int = discipleFacade.autoFillLawEnforcementSlots()
fun GameEngine.getDiscipleAggregate(discipleId: String): DiscipleAggregate? = discipleFacade.getDiscipleAggregate(discipleId)
fun GameEngine.getAllDiscipleAggregates(): List<DiscipleAggregate> = discipleFacade.getAllDiscipleAggregates()
suspend fun GameEngine.updateFocusedDisciple(discipleId: String) = discipleFacade.updateFocusedDisciple(discipleId)
suspend fun GameEngine.dismissDisciple(discipleId: String) = discipleFacade.dismissDisciple(discipleId)
fun GameEngine.giveItemToDisciple(discipleId: String, itemId: String, itemType: String) = discipleFacade.giveItemToDisciple(discipleId, itemId, itemType)
fun GameEngine.assignManual(discipleId: String, stackId: String) = discipleFacade.assignManual(discipleId, stackId)
fun GameEngine.removeManual(discipleId: String, instanceId: String) = discipleFacade.removeManual(discipleId, instanceId)
fun GameEngine.recruitDiscipleFromList(discipleId: String) = discipleFacade.recruitDiscipleFromList(discipleId)
suspend fun GameEngine.rewardItemsToDisciple(discipleId: String, items: List<RewardSelectedItem>) = discipleFacade.rewardItemsToDisciple(discipleId, items)
fun GameEngine.updateElderSlots(newElderSlots: ElderSlots) = discipleFacade.updateElderSlots(newElderSlots)
fun GameEngine.assignDirectDisciple(elderSlotType: String, slotIndex: Int, discipleId: String, discipleName: String, discipleRealm: String, discipleSpiritRootColor: String) = discipleFacade.assignDirectDisciple(elderSlotType, slotIndex, discipleId, discipleName, discipleRealm, discipleSpiritRootColor)
fun GameEngine.removeDirectDisciple(elderSlotType: String, slotIndex: Int) = discipleFacade.removeDirectDisciple(elderSlotType, slotIndex)
suspend fun GameEngine.updateDiscipleStatus(discipleId: String, status: DiscipleStatus) = discipleFacade.updateDiscipleStatus(discipleId, status)
fun GameEngine.assignDiscipleToLibrarySlot(slotIndex: Int, discipleId: String, discipleName: String) = discipleFacade.assignDiscipleToLibrarySlot(slotIndex, discipleId, discipleName)
fun GameEngine.removeDiscipleFromLibrarySlot(slotIndex: Int) = discipleFacade.removeDiscipleFromLibrarySlot(slotIndex)
