@echo off
REM SPIR-V Shader 编译脚本
REM 需要 Vulkan SDK 的 glslc 编译器
REM 下载: https://vulkan.lunarg.com/sdk/home
REM
REM 使用方式:
REM   compile_shaders.bat
REM
REM 输出: shaders/*.spv 和 shaders/shaders.h (C 头文件)

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set SHADER_DIR=%SCRIPT_DIR%

REM 尝试查找 glslc（Windows 默认路径）
set GLSLC=glslc.exe
where glslc >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    if exist "C:\VulkanSDK\Bin\glslc.exe" (
        set GLSLC=C:\VulkanSDK\Bin\glslc.exe
    ) else (
        echo WARNING: glslc not found in PATH or C:\VulkanSDK
        echo Please install Vulkan SDK from https://vulkan.lunarg.com/sdk/home
        echo Or add glslc.exe location to your PATH.
        echo.
        echo Compiling as best effort...
    )
)

REM 编译顶点着色器
echo Compiling sprite.vert...
"%GLSLC%" "%SHADER_DIR%\sprite.vert" -o "%SHADER_DIR%\sprite.vert.spv" 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo Warning: glslc not available, creating placeholder SPIR-V
)

REM 编译片段着色器
echo Compiling sprite.frag...
"%GLSLC%" "%SHADER_DIR%\sprite.frag" -o "%SHADER_DIR%\sprite.frag.spv" 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo Warning: glslc not available, creating placeholder SPIR-V
)

REM 生成 C 头文件（嵌入后的字节数组）
echo Generating shaders.h...
(
    echo #pragma once
    echo // Auto-generated by compile_shaders.bat
    echo // Do not edit manually — re-run compile_shaders.bat to regenerate
    echo.
    echo #ifdef __cplusplus
    echo extern "C" {
    echo #endif
) > "%SHADER_DIR%\shaders.h"

if exist "%SHADER_DIR%\sprite.vert.spv" (
    python -c "
import struct, sys
with open('%SHADER_DIR%\\sprite.vert.spv', 'rb') as f:
    data = f.read()
words = struct.unpack('I' * (len(data)//4), data)
print('static const uint32_t sprite_vert_spv[] = {')
for i in range(0, len(words), 8):
    chunk = ', '.join(f'0x{w:08X}' for w in words[i:i+8])
    print(f'    {chunk},')
print('};')
print(f'static const size_t sprite_vert_spv_size = {len(data)};')
" >> "%SHADER_DIR%\shaders.h" 2>nul
) else (
    echo // sprite.vert.spv not available — pipeline will use placeholder >> "%SHADER_DIR%\shaders.h"
)

if exist "%SHADER_DIR%\sprite.frag.spv" (
    python -c "
import struct
with open('%SHADER_DIR%\\sprite.frag.spv', 'rb') as f:
    data = f.read()
words = struct.unpack('I' * (len(data)//4), data)
print('static const uint32_t sprite_frag_spv[] = {')
for i in range(0, len(words), 8):
    chunk = ', '.join(f'0x{w:08X}' for w in words[i:i+8])
    print(f'    {chunk},')
print('};')
print(f'static const size_t sprite_frag_spv_size = {len(data)};')
" >> "%SHADER_DIR%\shaders.h" 2>nul
) else (
    echo // sprite.frag.spv not available — pipeline will use placeholder >> "%SHADER_DIR%\shaders.h"
)

(
    echo.
    echo #ifdef __cplusplus
    echo }
    echo #endif
) >> "%SHADER_DIR%\shaders.h"

echo Done.
