@echo off
REM SPIR-V Shader compile script.
REM Requires glslc (Vulkan SDK, or Android NDK shader-tools' glslc.exe).
REM Usage: compile_shaders.bat
REM Output: shaders/*.spv and shaders/shaders.h (generated by gen_shaders_header.py)

setlocal enabledelayedexpansion
set SCRIPT_DIR=%~dp0
set SHADER_DIR=%SCRIPT_DIR%

REM --- Locate glslc: PATH -> C:\VulkanSDK -> Android NDK shader-tools ---
set GLSLC=glslc.exe
where glslc >nul 2>nul
if not %ERRORLEVEL%==0 (
    if exist "C:\VulkanSDK\Bin\glslc.exe" (
        set GLSLC=C:\VulkanSDK\Bin\glslc.exe
    ) else (
        for /d %%d in ("%LOCALAPPDATA%\Android\Sdk\ndk\*") do (
            if exist "%%d\shader-tools\windows-x86_64\glslc.exe" set GLSLC=%%d\shader-tools\windows-x86_64\glslc.exe
        )
    )
)
if not exist "%GLSLC%" (
    echo WARNING: glslc not found; .spv files may be stale/placeholder.
)
echo Using glslc: %GLSLC%

echo Compiling sprite.vert...
"%GLSLC%" "%SHADER_DIR%\sprite.vert" -o "%SHADER_DIR%\sprite.vert.spv" 2>nul
echo Compiling sprite.frag...
"%GLSLC%" "%SHADER_DIR%\sprite.frag" -o "%SHADER_DIR%\sprite.frag.spv" 2>nul
echo Compiling sky.vert...
"%GLSLC%" "%SHADER_DIR%\sky.vert" -o "%SHADER_DIR%\sky.vert.spv" 2>nul
echo Compiling sky.frag...
"%GLSLC%" "%SHADER_DIR%\sky.frag" -o "%SHADER_DIR%\sky.frag.spv" 2>nul

echo Generating shaders.h...
python "%SHADER_DIR%\gen_shaders_header.py" "%SHADER_DIR%"
if not %ERRORLEVEL%==0 (
    echo Error: gen_shaders_header.py failed
    exit /b 1
)

echo Done.
